// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9EK1-pEy4TqIjGtMliedplY-2tX-_48U',
    appId: '1:202825633834:web:a0c78b3e67426cc738f353',
    messagingSenderId: '202825633834',
    projectId: 'ezposrheachen',
    authDomain: 'ezposrheachen.firebaseapp.com',
    storageBucket: 'ezposrheachen.firebasestorage.app',
    measurementId: 'G-J56CH56X27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxvD0IjCuZGJ84_lX9UsxJxpNErk_8UW8',
    appId: '1:202825633834:android:d9e0accd365a912e38f353',
    messagingSenderId: '202825633834',
    projectId: 'ezposrheachen',
    storageBucket: 'ezposrheachen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIxDWv5Fy-NBzFiCwPcEYaOezfJAqMXlY',
    appId: '1:202825633834:ios:9ea65c0183e7514c38f353',
    messagingSenderId: '202825633834',
    projectId: 'ezposrheachen',
    storageBucket: 'ezposrheachen.firebasestorage.app',
    androidClientId: '202825633834-dkrdc1id022dmib6c651777g2hpfom9p.apps.googleusercontent.com',
    iosClientId: '202825633834-f328lab6n782l8dh74i59lcbappqvhd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezposfinalproj',
  );
}
